---
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: iot-cluster-repl
  namespace: clickhouse
spec:
  configuration:
    clusters:
    - layout:
        replicasCount: 2
        shardsCount: 3
      name: iot-cluster
    users:
      benchmark/networks/ip:
      - 0.0.0.0/0
      benchmark/password: benchmark123
      default/networks/ip:
      - 0.0.0.0/0
      default/password: ""
    zookeeper:
      nodes:
      - host: zookeeper.zoons.svc.cluster.local
      - host: zookeeper-0.zookeepers.zoons.svc.cluster.local
      - host: zookeeper-1.zookeepers.zoons.svc.cluster.local
      - host: zookeeper-2.zookeepers.zoons.svc.cluster.local
  defaults:
    templates:
      dataVolumeClaimTemplate: default
      podTemplate: clickhouse-server
  templates:
    podTemplates:
    - name: clickhouse-server
      spec:
        nodeSelector:
          node_group: clickhouse_nodes
        tolerations:
        - key: clickhouse
          value: "true"
          effect: NoSchedule
        containers:
        - image: clickhouse/clickhouse-server:24.1
          name: clickhouse
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
    volumeClaimTemplates:
    - name: default
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gp3