apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-perf
  namespace: pulsar
  labels:
    app: producer-perf
spec:
  replicas: 2  # Number of producer instances
  selector:
    matchLabels:
      app: producer-perf
  template:
    metadata:
      labels:
        app: producer-perf
    spec:
      containers:
      - name: producer-perf
        image: producer-perf:latest
        imagePullPolicy: IfNotPresent
        env:
        # Device ID Distribution Configuration
        - name: TOTAL_DEVICE_COUNT
          value: "17000"
        - name: NUM_REPLICAS
          value: "2"  # Must match the replicas count above
        
        # Pulsar Configuration
        - name: PULSAR_URL
          value: "pulsar://pulsar-broker:6650"
        - name: PULSAR_TOPIC
          value: "persistent://public/default/iot-sensor-data"
        
        # Performance Configuration
        - name: MESSAGE_RATE
          value: "1000"
        - name: NUM_MESSAGES
          value: "0"  # 0 = unlimited
        - name: STATS_INTERVAL
          value: "10"
        
        # AVRO Configuration
        - name: USE_AVRO
          value: "true"
        
        # JVM Configuration
        - name: JAVA_OPTS
          value: "-Xms512m -Xmx1024m"
        
        # Pod identification for device ID calculation
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep IoTPerformanceProducer"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep IoTPerformanceProducer"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: producer-perf-service
  namespace: pulsar
  labels:
    app: producer-perf
spec:
  selector:
    app: producer-perf
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP
