apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-producer
  namespace: iot-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-producer
  template:
    metadata:
      labels:
        app: iot-producer
    spec:
      containers:
        - name: producer
          image: iot-producer:latest
          imagePullPolicy: Never  # For local Kind cluster
          env:
            - name: PULSAR_URL
              value: "pulsar://pulsar:6650"
            - name: PULSAR_TOPIC
              value: "persistent://public/default/iot-sensor-data"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"