apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: iot-pipeline
spec:
  type: ClusterIP
  ports:
    - name: pulsar
      port: 6650
      targetPort: 6650
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: pulsar
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pulsar
  namespace: iot-pipeline
spec:
  serviceName: pulsar
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar:latest
          command: ["bin/pulsar", "standalone"]
          ports:
            - containerPort: 6650
              name: pulsar
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: pulsar-data
              mountPath: /pulsar/data
          env:
            - name: PULSAR_MEM
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
  volumeClaimTemplates:
    - metadata:
        name: pulsar-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi