---
apiVersion: v1
kind: Namespace
metadata:
  name: zoons
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: zoons
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: prometheus
    port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: zookeeper
    what: node
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeepers
  namespace: zoons
spec:
  clusterIP: None
  ports:
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    app: zookeeper
    what: node
  type: ClusterIP
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pod-disruption-budget
  namespace: zoons
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: zoons
spec:
  podManagementPolicy: Parallel
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeepers
  template:
    metadata:
      annotations:
        prometheus.io/port: "7000"
        prometheus.io/scrape: "true"
      labels:
        app: zookeeper
        what: node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zookeeper
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - bash
        - -x
        - -c
        - |
          SERVERS=3 &&
          HOST=`hostname -s` &&
          DOMAIN=`hostname -d` &&
          CLIENT_PORT=2181 &&
          SERVER_PORT=2888 &&
          ELECTION_PORT=3888 &&
          PROMETHEUS_PORT=7000 &&
          ZOO_DATA_DIR=/var/lib/zookeeper/data &&
          ZOO_DATA_LOG_DIR=/var/lib/zookeeper/datalog &&
          {
            echo "clientPort=${CLIENT_PORT}"
            echo 'tickTime=2000'
            echo 'initLimit=300'
            echo 'syncLimit=10'
            echo 'maxClientCnxns=2000'
            echo 'maxTimeToWaitForEpoch=2000'
            echo 'maxSessionTimeout=60000000'
            echo "dataDir=${ZOO_DATA_DIR}"
            echo "dataLogDir=${ZOO_DATA_LOG_DIR}"
            echo 'autopurge.snapRetainCount=10'
            echo 'autopurge.purgeInterval=1'
            echo 'preAllocSize=131072'
            echo 'snapCount=3000000'
            echo 'leaderServes=yes'
            echo 'standaloneEnabled=false'
            echo '4lw.commands.whitelist=*'
            echo 'metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider'
            echo "metricsProvider.httpPort=${PROMETHEUS_PORT}"
            echo "zookeeper.skipACL=true"
          } > /conf/zoo.cfg &&
          {
            echo "zookeeper.root.logger=CONSOLE"
            echo "zookeeper.console.threshold=INFO"
            echo "log4j.rootLogger=\${zookeeper.root.logger}"
            echo "log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender"
            echo "log4j.appender.CONSOLE.Threshold=\${zookeeper.console.threshold}"
            echo "log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout"
            echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n"
          } > /conf/log4j.properties &&
          echo 'JVMFLAGS="-Xms128M -Xmx1G -XX:ActiveProcessorCount=8 -XX:+AlwaysPreTouch -Djute.maxbuffer=8388608 -XX:MaxGCPauseMillis=50"' > /conf/java.env &&
          if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
              NAME=${BASH_REMATCH[1]}
              ORD=${BASH_REMATCH[2]}
          else
              echo "Failed to parse name and ordinal of Pod"
              exit 1
          fi &&
          mkdir -p ${ZOO_DATA_DIR} &&
          mkdir -p ${ZOO_DATA_LOG_DIR} &&
          export MY_ID=$((ORD+1)) &&
          echo $MY_ID > $ZOO_DATA_DIR/myid &&
          for (( i=1; i<=$SERVERS; i++ )); do
              echo "server.$i=$NAME-$((i-1)).$DOMAIN:$SERVER_PORT:$ELECTION_PORT" >> /conf/zoo.cfg;
          done &&
          if [[ $SERVERS -eq 1 ]]; then
              echo "group.1=1" >> /conf/zoo.cfg;
          else
              echo "group.1=1:2:3" >> /conf/zoo.cfg;
          fi &&
          chown -Rv zookeeper "$ZOO_DATA_DIR" "$ZOO_DATA_LOG_DIR" "$ZOO_LOG_DIR" "$ZOO_CONF_DIR" &&
          zkServer.sh start-foreground
        image: docker.io/zookeeper:3.8.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - bash
            - -c
            - OK=$(echo ruok | nc 127.0.0.1 2181); if [[ "$OK" == "imok" ]]; then
              exit 0; else exit 1; fi
          initialDelaySeconds: 10
          timeoutSeconds: 5
        name: kubernetes-zookeeper
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: server
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        - containerPort: 7000
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - OK=$(echo ruok | nc 127.0.0.1 2181); if [[ "$OK" == "imok" ]]; then
              exit 0; else exit 1; fi
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: datadir-volume
      nodeSelector:
        workload: general
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: datadir-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: gp3