apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-metrics
  namespace: flink-benchmark
  labels:
    app: flink
    component: jobmanager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
      protocol: TCP
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-metrics
  namespace: flink-benchmark
  labels:
    app: flink
    component: taskmanager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
      protocol: TCP
  selector:
    app: flink
    component: taskmanager
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flink-metrics
  namespace: flink-benchmark
  labels:
    app: flink
    release: pulsar  # Important: matches Prometheus Operator release name
spec:
  selector:
    matchLabels:
      app: flink
  namespaceSelector:
    matchNames:
      - flink-benchmark
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics

