apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: flink-metrics
  namespace: flink-benchmark
  labels:
    app: flink
    component: metrics
spec:
  selector:
    matchLabels:
      app: flink-metrics
  namespaceSelector:
    matchNames:
      - flink-benchmark
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-metrics
  namespace: flink-benchmark
  labels:
    app: flink-metrics
    component: jobmanager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
      protocol: TCP
  selector:
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-metrics
  namespace: flink-benchmark
  labels:
    app: flink-metrics
    component: taskmanager
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
      protocol: TCP
  selector:
    component: taskmanager
